### PR TITLE
Adding preview option to fzf_open

### PR DESCRIPTION
**Pull request by dpayne**
This adds a preview option to the open command. I default to using `head -100` as the preview option but I also added support for specifying the pager. For example, `bind \cp '__fzf_open --editor --preview="bat --color always {}"'` would make use of `bat` to show a nice preview window. I also added used `ls -al` for showing directories, this is mostly to show something reasonable for directories.

fzf_open with preview

### CODE REVIEW

**Comment by jethrokuan** [comment]
This looks good, but something similar is offered with `__fzf_complete` (try `set -U FZF_COMPLETE 1`, and pressing `tab` in any directory). Since this doesn't affect functionality, I'm happy to merge it in, but I'd like you to first consider if it satisfies your needs, and if not, whether simply adding a variable to customize the pager would be sufficient.

**Comment by jethrokuan** [comment]
I'm not sure how people actually use this repo, but I think it's rare for an end user to inspect the code and find features that are supported by default, but not bound. It seems like the only way to use the feature you're adding here is to bind `__fzf_open` manually to a key, and figuring out that the `--preview` flag exists.  As you mentioned, you'd like 2 different versions of `__fzf_open`, showing previews only when opening a file in vim. 

So here I see two options:

1. Document the presence of the `--preview` flag.
2. make it a variable that can toggle the preview, that defaults to none. That way, people can choose whether to turn on or off the feature. In your case, you can leave it as the default off, and create a keybinding for one that has it on (by setting it locally).

Hope that makes sense to you.

**Comment by dpayne** [comment]
I updated the PR pretty significantly. I pulled out the preview command so that I wasn't duplicating the code in two places. It also enable me to specify the preview commands for both the tab complete and the open.

**Comment by jethrokuan** [comment]
Just pulled down your repo and tried it, works for me, great work! Thanks 😄

**Pull request merged**
