### PR TITLE
Implemented disown

### PR DESCRIPTION
**Pull request by serch037**

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@serch037 Keep in mind that `disown` is a fish 2.6 builtin and fzf's current fish version requirements are >=2.4. This is ultimately up to @jethrokuan to decide, but please update the documentation to reflect the new version requirement.

**Comment by jethrokuan** [comment]
I'm not entirely convinced that disowning the process is useful. Can you elaborate on why you think it would be the case?

**Comment by serch037** [comment]
Well in my use case, disown is useful because it allows me to re-use the same terminal (even more with a drop-down terminal) as a fast launcher for files and directories, in the style of Alfred (in MacOS). Whereas without disown, the terminal session becomes blocked until the process is finished (that is, until I close the file), this prevents me from opening multiple files on the same session, or using the same terminal session for something else.

**Comment by jethrokuan** [comment]
I see, that makes sense.

**Pull request merged**
