### PR TITLE
Add example for `fd` in the README

### PR DESCRIPTION
**Pull request by skorokithakis**

### CODE REVIEW

**Comment by skorokithakis** [comment]
Looking at it, I think the `ag` example might be wrong as well, or at least it didn't work on a simple example I tried?

**Comment by skorokithakis** [comment]
Certainly, although I don't know how to fix the `ag` example, since I don't know the variable name for the text being completed.

**Comment by jethrokuan** [comment]
`ag -l . \$dir 2> /dev/null` seems to work best for me.

**Comment by skorokithakis** [comment]
I have changed the `ag` example as well, seems to work well!

**Comment by jethrokuan** [comment]
Thanks!

**Pull request merged**
