### PR TITLE
Add init.fish to support oh-my-fish, add installation instructions to README.md

### PR DESCRIPTION
**Pull request by rominf**

### CODE REVIEW

**Comment by jethrokuan** [comment]
:+1: Thanks!

**Comment by EMayej** [comment]
@rominf @jethrokuan 
Hi guys. fisherman can't load this file, how could we support both fisherman and oh-my-fish?

report this error
`
source: Error encountered while sourcing file '/Users/EMayej/.config/fish/conf.d/conf.d/fzf.fish':
source: No such file or directory
`

for this line
`
source (dirname (status --current-filename))/conf.d/fzf.fish
`

**Comment by EMayej** [comment]
@rominf looks like fisherman tries to install both files under `conf.d`. Although the init.fish file is in project root

```
 ~/.config/fish/conf.d  la | grep fzf
lrwxr-xr-x   1 EMayej  staff    51B Sep 30 14:25 fzf.fish -> /Users/EMayej/.config/fisherman/fzf/conf.d/fzf.fish
lrwxr-xr-x   1 EMayej  staff    45B Sep 30 14:25 fzf.init.fish -> /Users/EMayej/.config/fisherman/fzf/init.fish
```

**Comment by EMayej** [comment]
@rominf maybe a easy solution is just rename `conf.d/fzf.fish` to `init.fish`. In that way fisherman will put init.fish under `conf.d` while oh-my-fish is also happy

**Comment by rominf** [comment]
@jethrokuan, see #77 for a fix.

**Comment by jethrokuan** [comment]
I merged the fix for now. imo this is sourcing from `conf.d` should be something omf should include, since it's officially supported by fish-shell.

**Pull request merged**
